---
- name: Desplegar aplicacion con Docker Compose
  hosts: web
  become: true

  tasks:
    - name: Crear directorio principal del proyecto
      file:
        path: /opt/asir-final
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Crear directorio app
      file:
        path: /opt/asir-final/app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Crear directorio docker
      file:
        path: /opt/asir-final/docker
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copiar codigo de la aplicacion
      copy:
        src: "{{ playbook_dir }}/../../app/"
        dest: /opt/asir-final/app/
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copiar dockerfile
      copy:
        src: "{{ playbook_dir }}/../../docker/dockerfile"
        dest: /opt/asir-final/docker/dockerfile
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Copiar docker-compose.yml
      copy:
        src: "{{ playbook_dir }}/../../docker/docker-compose.yml"
        dest: /opt/asir-final/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Levantar aplicacion
      shell: docker compose up -d --build
      args:
        chdir: /opt/asir-final
      register: deploy_result

    - name: Mostrar salida del despliegue
      debug:
        var: deploy_result.stdout_lines

    - name: Ver contenedores
      shell: docker compose ps
      args:
        chdir: /opt/asir-final
      register: compose_ps
      changed_when: false

    - name: Mostrar estado de contenedores
      debug:
        var: compose_ps.stdout_lines