name: Deploy to EC2 with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Sustituir IP en inventario
        run: |
          sed -i "s/TU_IP_PUBLICA_EC2/${{ secrets.EC2_HOST }}/g" ansible/inventory/hosts.ini

      - name: Ejecutar playbook
        run: |
          ansible-playbook ansible/playbooks/site.yml