name: Deploy to EC2 with Ansible

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Limpiar repos problematicos
        run: |
          sudo rm -f /etc/apt/sources.list.d/azure-cli.list
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list

      - name: Instalar Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Sustituir IP en inventario
        run: |
          sed -i "s/TU_IP_PUBLICA_EC2/${{ secrets.EC2_HOST }}/g" ansible/inventory/hosts.ini

      - name: Mostrar inventario resultante
        run: |
          cat ansible/inventory/hosts.ini

      - name: Probar conectividad Ansible
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible all -i ansible/inventory/hosts.ini -m ping --private-key ~/.ssh/id_ed25519

      - name: Ejecutar playbook completo
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ansible/inventory/hosts.ini ansible/playbooks/site.yml --private-key ~/.ssh/id_ed25519